apiVersion: v1
kind: Pod
metadata:
  name: jnlp
  namespace: jenkins
spec:
  containers:
  - name: jnlp
    image: khiemdevops0902/test01:1.2
    command:
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: kubectl-binary
      mountPath: /usr/local/bin/kubectl
      readOnly: true
  volumes:
    - name: kubectl-binary
      hostPath:
        path: /usr/bin/kubectl
